# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy scan, and more:
# https://aka.ms/yaml
trigger:
- none

# defined parameters to select environments
parameters:
  - name: environment
    displayName: Environment
    values:
      - dev
      - test


  - name: repo_url
    displayName: Azure Container Repositry URl 
    default: axrdemo.azurecr.io

  - name: azure_rg
    displayName: Azure resource group
    default: provision-scripts

  - name: azure_storage
    displayName: Azure Storage Account Name
    default: azurestorage

  - name: azure_storage_container
    displayName: Azure Storage Container
    default: terraform

  - name: azurespn
    displayName: Azure Service principal
    default: "DemoSpn"

  - name: acr_serviceconnection
    displayName: ACR SPN
    default: acr

  - name: aks_serviceconnection
    displayName: AKS SPN
    default: aks

  - name: infra
    displayName: Infra Provision
    type: boolean
    default: false

  - name: build
    displayName: Build Docker Image
    type: boolean
    default: false

  - name: deploy
    displayName: Deploy AKS Cluster
    type: boolean
    default: false


# Defined variables aks_serviceconnection, acr_serviceconnection, repo_url are must to update for new configuration
variables:
  imageName_vote: vote
  imageName_result: result
  imageName_worker: worker
  aks_serviceconnection: ${{ parameters.aks_serviceconnection }}
  acr_serviceconnection: ${{ parameters.acr_serviceconnection }}
  namespaces: 'vote'
  password: 'postgres'
  secretName: 'acrsecret'
  secretNameDb: 'dbsecret'
  tags: 'latest'

# Stage to build/compile the code
stages:
- ${{ if eq(parameters.infra, true) }}:
  - stage: Infra
    displayName: Infra provisioning
    jobs:
    - job: Compile
      displayName: 'Infra_${{ parameters.environment }} '
      pool:
                vmImage: 'ubuntu-latest'
      steps:
        - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
          displayName: 'Install Terraform 0.13.0'
          inputs:
            terraformVersion: 0.13.0

        - powershell: |
              Set-Content -Path backend.tf -Value @"
              terraform{
                backend "azurerm"{
                }
              }
              "@
          workingDirectory: "$(System.DefaultWorkingDirectory)/Infra_provision"
          displayName: "Configure tf backend"

        - task: TerraformTaskV1@0
          displayName: "Terraform Init"
          inputs:
            provider: "azurerm"
            command: "init"
            workingDirectory: "$(System.DefaultWorkingDirectory)/Infra_provision"
            backendServiceArm: ${{ parameters.azurespn }}
            backendAzureRmResourceGroupName: ${{ parameters.azure_rg }}
            backendAzureRmStorageAccountName: ${{ parameters.azure_storage }}
            backendAzureRmContainerName: ${{ parameters.azure_storage_container }}
            backendAzureRmKey: "terraform_${{ parameters.environment }}.tfstate"

        - task: TerraformTaskV1@0
          displayName: "Terraform Plan"
          # condition: and(succeeded(), eq('${{ parameters.enabled }}', true))
          inputs:
            provider: "azurerm"
            command: "plan"
            workingDirectory: "$(System.DefaultWorkingDirectory)/Infra_provision"
            commandOptions: '-out=tfplan -lock=false'
            environmentServiceNameAzureRM: ${{ parameters.azurespn }}

        - task: TerraformTaskV1@0
          name: terraformApply
          # enabled: ${{ parameters.confirmApply }}
          # condition: and(succeeded(), eq('${{ parameters.enabled }}', true))
          inputs:
            provider: "azurerm"
            command: "apply"
            workingDirectory: "$(System.DefaultWorkingDirectory)/Infra_provision"
            commandOptions: "-lock=false tfplan"
            environmentServiceNameAzureRM: ${{ parameters.azurespn }}
          continueOnError: true 

- ${{ if eq(parameters.build, true) }}:
  - stage: BuildDockerImage
    displayName: BuildDockerImage
#    dependsOn: Infra
    jobs:
      - job: Compile
        displayName: BuildDockerImage
        pool:
          vmImage: 'ubuntu-latest'
        steps:

        # Building the vote docker image and pushing it to ACR  
        - task: Docker@2
          displayName: 'building vote image'
          inputs:
            containerRegistry: '$(acr_serviceconnection)'
            repository: '$(imageName_vote)'
            command: 'buildAndPush'
            Dockerfile: '$(Build.SourcesDirectory)/vote/Dockerfile'
            tags: |
              $(tags)

       # Building the result docker image and pushing it to ACR  
        - task: Docker@2
          displayName: 'building result image'
          inputs:
            containerRegistry: '$(acr_serviceconnection)'
            repository: '$(imageName_result)'
            command: 'buildAndPush'
            Dockerfile: '$(Build.SourcesDirectory)/result/Dockerfile'
            tags: |
              $(tags)

        # Building the worker docker image and pushing it to ACR 
        - task: Docker@2
          displayName: 'building worker image'
          inputs:
            containerRegistry: '$(acr_serviceconnection)'
            repository: '$(imageName_worker)'
            command: 'buildAndPush'
            Dockerfile: '$(Build.SourcesDirectory)/worker/Dockerfile'
            tags: |
              $(tags)

        # publish kubernetes yaml files for deployment
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(Pipeline.Workspace)/s/azure_kubernetes'
            artifact: 'manifests'
            publishLocation: 'pipeline'

#stage to deploy the kubernetes objects on cluster
- ${{ if eq(parameters.deploy, true) }}:
  - stage: Deployk8scluster
    displayName: Deploy AKS cluster
    dependsOn: BuildDockerImage
    jobs:
    - job: deploy
      displayName:  deploy-${{parameters.environment}}
      pool:
       vmImage: 'ubuntu-latest'
      steps:
           - task: DownloadPipelineArtifact@2
             inputs:
               buildType: 'current'
               artifactName: 'manifests'
               targetPath: '$(Pipeline.Workspace)/manifests'

           - task: Kubernetes@1
             displayName: create namespace
             inputs:
               connectionType: 'Kubernetes Service Connection'
               kubernetesServiceEndpoint: '$(aks_serviceconnection)'
               command: 'create'
               arguments: 'namespace $(namespaces)'
               secretType: 'dockerRegistry'
               containerRegistryType: 'Azure Container Registry'

           # creating secret to authnticate with Azure contianer registery
           - task: KubernetesManifest@0
             displayName: 'Create Secrets ACR'
             inputs:
               action: 'createSecret'
               kubernetesServiceConnection: '$(aks_serviceconnection)'
               namespace: '$(namespaces)'
               secretType: 'dockerRegistry'
               secretName: '$(secretName)'
               dockerRegistryEndpoint: '$(acr_serviceconnection)'

            # creating secret to create database username and password encrypted
           - task: KubernetesManifest@0
             displayName: 'create secret DB'
             inputs:
               action: 'createSecret'
               kubernetesServiceConnection: '$(aks_serviceconnection)'
               namespace: '$(namespaces)'
               secretType: 'generic'
               secretName: '$(secretNameDb)'
               secretArguments: '--from-literal=username=postgres --from-literal=password="$(password)"'  # password's value defined in azure pipline varibales


           #Replacing secret name in db-deployment.yml file
           - task: replacetokens@5
             inputs:
               rootDirectory: '$(Pipeline.Workspace)/manifests'
               targetFiles: 'db-deployment.yaml'
               encoding: 'auto'
               tokenPattern: 'custom'
               tokenPrefix: '#{'
               tokenSuffix: '}#'
               writeBOM: true
               actionOnMissing: 'warn'
               keepToken: false
               actionOnNoFiles: 'continue'
               enableTransforms: false
               useLegacyPattern: false
               enableTelemetry: true

         # Fetching image from ACR for vote apps and deploying it on AKS
           - task: KubernetesManifest@0
             displayName: 'Deploy vote App Kubernetes'
             inputs:
               action: 'deploy'
               kubernetesServiceConnection: '$(aks_serviceconnection)'
               namespace: '$(namespaces)'
               manifests: |
                 $(Pipeline.Workspace)/manifests/vote-deployment.yaml
                 $(Pipeline.Workspace)/manifests/vote-service.yaml
               containers: '${{parameters.repo_url}}/$(imageName_vote):$(tags)'
               imagePullSecrets: '$(secretName)'
   
          # deploying image for Redis application on AKS
           - task: KubernetesManifest@0
             displayName: 'Deploy Redis Kubernetes'
             inputs:
               action: 'deploy'
               kubernetesServiceConnection: '$(aks_serviceconnection)'
               namespace: '$(namespaces)'
               manifests: |
                 $(Pipeline.Workspace)/manifests/redis-deployment.yaml
                 $(Pipeline.Workspace)/manifests/redis-service.yaml

          # deploying image for Postgres database on AKS
           - task: KubernetesManifest@0
             displayName: 'Deploy DB Kubernetes'
             inputs:
               action: 'deploy'
               kubernetesServiceConnection: '$(aks_serviceconnection)'
               namespace: '$(namespaces)'
               manifests: |
                 $(Pipeline.Workspace)/manifests/db-deployment.yaml
                 $(Pipeline.Workspace)/manifests/db-service.yaml

           # Fetching image from ACR for worker apps and deploying it on AKS
           - task: KubernetesManifest@0
             displayName: 'Deploy worker Kubernetes'
             inputs:
               action: 'deploy'
               kubernetesServiceConnection: '$(aks_serviceconnection)'
               namespace: '$(namespaces)'
               manifests: |
                 $(Pipeline.Workspace)/manifests/worker-deployment.yaml
                 $(Pipeline.Workspace)/manifests/autoscale-worker-deployment.yaml
                 $(Pipeline.Workspace)/manifests/worker-service.yaml
               containers: '${{parameters.repo_url}}/$(imageName_worker):$(tags)'
               imagePullSecrets: '$(secretName)'

           # Fetching image from ACR for result apps and deploying it on AKS
           - task: KubernetesManifest@0
             displayName: 'Deploy result app Kubernetes'
             inputs:
               action: 'deploy'
               kubernetesServiceConnection: '$(aks_serviceconnection)'
               namespace: '$(namespaces)'
               manifests: |
                 $(Pipeline.Workspace)/manifests/result-deployment.yaml
                 $(Pipeline.Workspace)/manifests/result-service.yaml
               containers: '${{parameters.repo_url}}/$(imageName_result):$(tags)'
               imagePullSecrets: '$(secretName)'
