# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- None

parameters:
  - name: environment
    displayName: Environment
    default: dev
    type: string
    values:
      - dev
      - test
      - stage
      - prod


variables:
  imageName_vote: vote
  imageName_result: result
  tags: '$(Build.BuildId)'
  replicaNo: 2
  aks_serviceconnection: ''
  namespaces: ''
  repo_url: 'akacrdemo.azurecr.io'
  secretName: 'acrsecret'

stages:
  - stage: Build
    displayName: Build App
    jobs:
      - job: Compile
        displayName: 'Build Vote App'
        pool:
          name: 'Default'
        steps:
        - task: Docker@2
          displayName: 'building vote image'
          inputs:
            containerRegistry: 'acr'
            repository: '$(imageName_vote)'
            command: 'buildAndPush'
            Dockerfile: '$(Build.SourcesDirectory)/vote/Dockerfile'
            tags: |
              $(tags)
              latest

        - task: Docker@2
          displayName: 'building result image'
          inputs:
            containerRegistry: 'acr'
            repository: '$(imageName_result)'
            command: 'buildAndPush'
            Dockerfile: '$(Build.SourcesDirectory)/result/Dockerfile'
            tags: |
              $(tags)
              latest
        
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(Pipeline.Workspace)/s/k8s-specifications'
            artifact: 'manifests'
            publishLocation: 'pipeline'
