# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- None

parameters:
  - name: environment
    displayName: Environment
    default: dev
    type: string
    values:
      - dev
      - test
      - stage
      - prod


  - name: build
    displayName: Build code
    type: boolean
    default: false

  - name: deploy
    displayName: Deploy Code
    type: boolean
    default: false

variables:
 - group: aks_${{ parameters.environment }}
 - name: imageName
   value: nginx
 - name: tags
   value: '$(Build.BuildId)'
 - name: replicaNo
   value: 2  

stages:
- ${{ if eq(parameters.build, true) }}:
  - stage: Build
    displayName: Build App
    jobs:
      - job: Compile
        displayName: 'Build'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'acr'
            repository: '$(imageName)'
            command: 'buildAndPush'
            Dockerfile: '$(Build.SourcesDirectory)/docker-project/Dockerfile'
            tags: |
              $(tags)
#              latest
        
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(Pipeline.Workspace)/s/docker-project'
            artifact: 'manifests'
            publishLocation: 'pipeline'
