apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: vote
  name: azure-db-back-hpa
spec:
  maxReplicas: 10 # define max replica count
  minReplicas: 1  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: db
  targetCPUUtilizationPercentage: 20 # target CPU utilization
