apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: vote
  name: azure-worker-back-hpa
spec:
  maxReplicas: 10 # define max replica count
  minReplicas: 1  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker
  targetCPUUtilizationPercentage: 50 # target CPU utilization