apiVersion: v1
kind: Service
metadata: 
  namespace: vote
  name: db
  labels: 
    app: db
spec: 
  clusterIP: None
  ports: 
  - name: db
    port: 5432
    targetPort: 5432
  selector: 
    app: db
  
