apiVersion: v1
kind: Service
metadata:
  name: result
  namespace: vote
  labels:
    app: result
spec:
  type: LoadBalancer
  ports:
  - port: 5001
    targetPort: 80
    name: result-service
  selector:
    app: result